---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/coder version
    register: coder_test_output
  - name: coder version
    debug:
      msg: '{{ coder_test_output.stdout }}'
