---
- name: Testing andrewrothstein.coder
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'coder version'
      ansible.builtin.command: coder version
      changed_when: false
      register: coder_test_output
    - name: Output from 'coder version'
      ansible.builtin.debug:
        msg: '{{ coder_test_output.stdout }}'
