---
- include_role:
    name: andrewrothstein.unarchive-deps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install at {{ coder_install_exe }}
  become: true
  stat:
    path: '{{ coder_install_exe }}'
  changed_when: false
  register: coder_binary
- when: not coder_binary.stat.exists
  block:
    - name: downloading {{ coder_url }} to {{ coder_tmp_archive }}
      become: true
      become_user: root
      get_url:
        url: '{{ coder_url }}'
        dest: '{{ coder_tmp_archive }}'
        checksum: '{{ coder_checksum }}'
        mode: 0644
    - name: mkdir -p {{ coder_install_dir }}
      become: true
      become_user: root
      file:
        path: '{{ coder_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive {{ coder_tmp_archive }} to {{ coder_install_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ coder_tmp_archive }}'
        dest: '{{ coder_install_dir }}'
        creates: '{{ coder_install_exe }}'
  always:
    - name: rm -f {{ coder_tmp_archive }}
      become: true
      become_user: root
      file:
        path: '{{ coder_tmp_archive }}'
        state: absent
- name: linking {{ coder_install_exe }} to {{ coder_link }}
  become: true
  become_user: root
  file:
    src: '{{ coder_install_exe }}'
    dest: '{{ coder_link }}'
    state: link
