---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_facts["distribution"] }}-{{ ansible_facts["distribution_release"] }}.yml'
        - '{{ ansible_facts["distribution"] }}.yml'
        - '{{ ansible_facts["os_family"] }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install at {{ coder_install_exe }}
  become: true
  ansible.builtin.stat:
    path: '{{ coder_install_exe }}'
  changed_when: false
  register: coder_binary
- name: Downloading and installing coder
  when: not coder_binary.stat.exists
  block:
    - name: Downloading {{ coder_url }} to {{ coder_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ coder_url }}'
        dest: '{{ coder_tmp_archive }}'
        checksum: '{{ coder_checksum }}'
        mode: '644'
    - name: Mkdir -p {{ coder_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ coder_install_dir }}'
        state: directory
        mode: '755'
    - name: Installing andrewrothstein.unarchivedeps
      ansible.builtin.include_role:
        name: andrewrothstein.unarchivedeps
    - name: Unarchive {{ coder_tmp_archive }} to {{ coder_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ coder_tmp_archive }}'
        dest: '{{ coder_install_dir }}'
        creates: '{{ coder_install_exe }}'
  always:
    - name: Rm -f {{ coder_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ coder_tmp_archive }}'
        state: absent
- name: Linking {{ coder_install_exe }} to {{ coder_link }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ coder_install_exe }}'
    dest: '{{ coder_link }}'
    state: link
